//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcStok._1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMusteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMusteriler()
        {
            this.tblSatis = new HashSet<tblSatis>();
        }
    
        public int musteriid { get; set; }

        [StringLength(50,ErrorMessage = "Maksimum 50 karakter girebilirsiniz.")]
        [Required(ErrorMessage = "Müþteri Adý Boþ Geçilemez.")]
        public string musteriad { get; set; }

        [StringLength(50, ErrorMessage = "Maksimum 50 karakter girebilirsiniz.")]
        [Required(ErrorMessage ="Müþteri Soyadý Boþ Geçilemez.")]
        public string musterisoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatis> tblSatis { get; set; }
    }
}
