//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcStok._1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrunler()
        {
            this.tblSatis = new HashSet<tblSatis>();
        }
    
        public int urunid { get; set; }
        //ürün ad
        [StringLength(50,ErrorMessage ="Ürün adý 0-50 karakter aralýðýnda olmalýdýr.",MinimumLength = 1)]
        public string urunad { get; set; }
        //marka
        [StringLength(50, ErrorMessage = "Marka 0-50 karakter aralýðýnda olmalýdýr.", MinimumLength = 1)]
        public string marka { get; set; }
        //kategori
        public Nullable<short> urunkategori { get; set; }
        //fiyat
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<byte> stok { get; set; }
    
        public virtual tblKategoriler tblKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatis> tblSatis { get; set; }
    }
}
